---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: directory
    path: content/blog
    label: blog
    create: documents
    match: "**/*"
    templates:
      - blog-post
  - type: directory
    path: content/projects
    label: projects
    create: documents
    match: "**/*"
    templates:
      - project
  - type: directory
    path: content/work-history
    label: Work history
    create: documents
    match: "**/*"
    templates:
      - work-history-item
upload_dir: static/uploads
public_path: "/static/uploads"
front_matter_path: ""
use_front_matter_path:
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: node:14-alpine
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
