---
label: project
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: name
  description: name of project
- name: image
  type: file
  config:
    maxSize: 64
  label: image
  description: square picture for the project
- name: date
  type: datetime
  label: date
  description: start date of project
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- name: tags
  type: tag_list
  default: []
  description: technologies used in this project
  label: tags
pages:
- content/projects/timsandberg-dot-com.md
